server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false